### ISSUE TITLE
Verwijder Socket.io

### ISSUE THREAD

**Issue by joostverdoorn** [joostverdoorn/webrtc#105]
We gebruiken socket.io zeer spaarzaam waardoor het handiger kan zijn om puur websockets te gebruiken

**Comment by jhs512** [comment]
Hellow sir.

i wanna play http://webrtc.jstfy.com/
but it doesn't work now.

i am interesting about your project.

plz let me see your demo site.

thanks

**Comment by karensg** [comment]
Hallo @joostverdoorn,
I am also very interested. Let's play!

**Comment by jhs512** [comment]
Thanks.~

but the demo site  ( http://webrtc.jstfy.com/ ) doesn't work now.

like this.

https://www.youtube.com/watch?v=1CN8EBaDC9M&feature=youtu.be

ps. i'm a korean and using chrome.

**Comment by jhs512** [comment]
Hello @karensg ,
Have you run this game successfully ?

ps. I'm trying to run this game on centos 7 but i've failed.
