### ISSUE TITLE
Nodegraph suddenly stops rendering

### ISSUE THREAD

**Issue by jabbink** [joostverdoorn/webrtc#17]

**Comment by jabbink** [comment]
NodeJS server sometimes decides to not return a call to the /nodes API.
A pagerefresh solves the problems generated by this and has no influence on the actual networking and I therefore see it as not important to fix now.

**Comment by joostverdoorn** [comment]
This will probably be worked on when we implement a more advanced version
of the network (graph) overview
- Joost Verdoorn*
  *
  *\* A\* Kromstraat 23a

2611 EP Delft
- T *+31 6 5120 2115
- E\* jpverdoorn@gmail.com
