### ISSUE TITLE
Als gebruiker, wil ik dat andere spelers altijd vloeiend voortbewegen

### ISSUE THREAD

**Issue by karensg** [joostverdoorn/webrtc#30]

**Comment by joostverdoorn** [comment]
Dit is een lastige. Hiervoor zullen we iets van dead reckoning moeten gebruiker: http://en.wikipedia.org/wiki/Dead_reckoning#Dead_reckoning_for_networked_games

Projectielen zullen een eigenaar moeten hebben die hun positie dicteert, en spelers hoogstwaarschijnlijk ook.
