### ISSUE TITLE
Als gebruiker, wil ik dat als een projectiel een speler raakt, dat de speler dood gaat

### ISSUE THREAD

**Issue by karensg** [joostverdoorn/webrtc#34]

**Comment by harrieatwork** [comment]
is 1 kogel direct dood & respawn? Je zou kunnen overwegen om een speler pas na x kogels dood te verklaren. Een energy bar is dan misschien noodzakelijk. Een speciale powerup  zou de energy weer naar 100% kunnen brengen.

**Comment by jabbink** [comment]
Het plan is om eerst de collision van een projectiel naar een ufo te detecteren en daar dan op te reageren. Wanneer het te makkelijk blijkt te zijn iemand een keer te raken gaan wij dit hierna pas veranderen.
